---
- name: Basic provisioning
  hosts: all
  become: true

  tasks:
    - name: Provision RedHat
      ansible.builtin.include_tasks: redhat.yml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Provision Debian
      ansible.builtin.include_tasks: debian.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Install yq 3.4.1
      get_url:
        url: https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
        dest: /usr/bin/yq
        mode: 0755
