---
- name: Basic provisioning
  hosts: all
  become: true

  tasks:
    - name: Provision RedHat
      ansible.builtin.include_tasks: redhat.yml
      when: ansible_facts['os_family'] == "RedHat"

    - name: Provision Debian
      ansible.builtin.include_tasks: debian.yml
      when: ansible_facts['os_family'] == "Debian"

    - name: Install yq 3.4.1
      get_url:
        url: https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
        dest: /usr/bin/yq
        mode: 0755

- name: Install k3s
  hosts: fedora
  become: true

  tasks:
    - name: Get k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: 0755

    - name: Install k3s
      shell: /tmp/k3s-install.sh

    - name: Remove install script
      file:
        path: /tmp/k3s-install.sh
        state: absent

- name: Install nerdctl
  hosts: all
  become: true

  tasks:
    - name: Install nerdctl
      ansible.builtin.unarchive:
        src: https://github.com/containerd/nerdctl/releases/download/v1.0.0/nerdctl-full-1.0.0-linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Set SETUID on nerdctl command
      shell: |
        chmod +s /usr/local/bin/nerdctl

    - name: Configure nerdctl to use k3s runtime
      ansible.builtin.copy:
        dest: /etc/nerdctl/nerdctl.toml
        mode: '0644'
        content: |
          # This is an example of /etc/nerdctl/nerdctl.toml .
          # Unrelated to the daemon's /etc/containerd/config.toml .

          debug          = false
          debug_full     = false
          address        = "unix:///run/k3s/containerd/containerd.sock"
          namespace      = "k8s.io"
          snapshotter    = "stargz"
          cgroup_manager = "cgroupfs"
          hosts_dir      = ["/etc/containerd/certs.d", "/etc/docker/certs.d"]
          experimental   = true

    - name: Enable buildkit service
      ansible.builtin.systemd:
        name: buildkit.service
        enabled: yes
        state: started

    - name: Configure buildkit to share images with k3s
      ansible.builtin.copy:
        dest: /etc/buildkit/buildkit.toml
        content: |
          [worker.oci]
            enabled = false

          [worker.containerd]
            enabled = true
            # namespace should be "k8s.io" for Kubernetes (including Rancher Desktop)
            namespace = "k8s.io"
