- name: Install utilities
  dnf:
    name:
      - gcc-c++
      - clang
      - ccache
      - glibc-devel.i686
      - libcap-devel
      - bpftool
      - git
      - make
      - cmake
      - wget
      - kernel-devel
      - libbpf-devel
      - elfutils-libelf-devel
      - perl-IPC-Cmd
      - NetworkManager-initscripts-ifcfg-rh
    state: latest

- name: Update system
  dnf:
    name: "*"
    state: latest

- name: which ccache
  ansible.builtin.command: which ccache
  register: ccache_path

- name: Create local bin directory
  ansible.builtin.file:
    path: /home/vagrant/.local/bin
    state: directory
    owner: vagrant
    group: vagrant

- name: gcc-ccache symlink
  ansible.builtin.file:
    src: "{{ ccache_path.stdout }}"
    dest: /home/vagrant/.local/bin/gcc
    owner: vagrant
    group: vagrant
    state: link

- name: g++-ccache symlink
  ansible.builtin.file:
    src: "{{ ccache_path.stdout }}"
    dest: /home/vagrant/.local/bin/g++
    owner: vagrant
    group: vagrant
    state: link

- name: Add $HOME/.local/bin to $PATH
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bash_profile
    line: PATH="/home/vagrant/.local/bin:$PATH"

- name: Don't use ccache by default
  ansible.builtin.lineinfile:
    path: /home/vagrant/.bash_profile
    line: export CCACHE_DISABLE=true

- name: Use vi as editor
  lineinfile:
    dest: /home/vagrant/.bash_profile
    line: export EDITOR=vi
