---
- name: Basic provisioning
  hosts: all
  become: true

  tasks:
    - name: Install utilities [dnf]
      dnf:
        name:
          - make
          - jq
          - wget
          - golang
          - kernel-devel
          - origin-clients
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install utilities [apt]
      apt:
        name:
          - make
          - jq
          - wget
          - golang
          - linux-headers-{{ ansible_kernel }}
        state: latest
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update system [dnf]
      dnf:
        name: "*"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: Update system [apt]
      apt:
        upgrade: yes
        update_cache: yes
        state: latest
      when: ansible_facts['os_family'] == "Debian"

    - name: Install yq 3.4.1
      get_url:
        url: https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64
        dest: /usr/bin/yq
        mode: 0755

- name: Install docker
  hosts: all
  become: true

  tasks:
    - name: Get docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/docker-install.sh
        mode: 0755

    - name: Install docker
      shell: /tmp/docker-install.sh

    - name: Remove install script
      file:
        path: /tmp/docker-install.sh
        state: absent

    - name: Configure and enable docker
      shell: |
        usermod -aG docker vagrant
        systemctl enable --now docker

- name: Install k3s
  hosts: fedora
  become: true

  tasks:
    - name: Get k3s install script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: 0755

    - name: Install k3s
      shell: /tmp/k3s-install.sh

    - name: Remove install script
      file:
        path: /tmp/k3s-install.sh
        state: absent

    - name: Copy k3s config file
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ playbook_dir }}/k3s.yaml"
        remote_src: yes
